name: base-build
on:
  workflow_call:
    inputs:
      path:
        description: 'build dirs'
        type: string
        required: true
      file:
        description: 'build output file'
        type: string
        required: true
      CI_GOOS:
        type: string
        required: true
      CI_GOARCH:
        type: string
        required: true
      TAGS:
        type: string
        default: ""

jobs:
  base-build:
    name: ${{inputs.file}}
    runs-on: ubuntu-20.04
    container:
      image: veinmind/go1.18:1.5.3-stretch
    env:
      CI_GOOS: ${{inputs.CI_GOOS}}
      CI_GOARCH: ${{inputs.CI_GOARCH}}
      TAGS: ${{inputs.TAGS}}
    steps:
      - uses: actions/checkout@v3
      - run: make platform.${{ inputs.file }} CI_GOOS=${{inputs.CI_GOOS}} CI_GOARCH=${{inputs.CI_GOARCH}} TAGS=${{inputs.TAGS}}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.file}}-${{inputs.CI_GOARCH}}
          path: ${{inputs.path}}/${{inputs.file}}_${{inputs.CI_GOOS}}_${{inputs.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{inputs.file}}-${{inputs.CI_GOARCH}}
          files: ${{inputs.path}}/${{inputs.file}}_${{inputs.CI_GOOS}}_${{inputs.CI_GOARCH}}