name: veinmind-tools-build
on:
  workflow_call:

jobs:
  # build go plugins with static enviroment
  build-plugins-amd64:
    strategy:
      fail-fast: false
      matrix:
        plugin: [
          veinmind-basic,
          veinmind-escalate,
          veinmind-iac,
          veinmind-log4j2,
          veinmind-malicious,
          veinmind-sensitive,
          veinmind-unsafe-mount,
          veinmind-vuln,
          veinmind-weakpass,
          veinmind-webshell,
          veinmind-runner,
        ]
        arch: [ amd64, arm64 ]
        include:
          - tags: community
            plugin: veinmind-malicious
          - tags: static
            plugin: veinmind-weakpass
    name: ${{ matrix.plugin }}
    runs-on: ubuntu-20.04
    env:
      CI_GOOS: linux
      CI_GOARCH: ${{ matrix.arch }}
      TAGS: ${{matrix.TAGS}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: sudo make install
      - run: go version && which go
      - run: sudo make platform.${{ matrix.plugin }} CI_GOOS=${{ env.CI_GOOS }} CI_GOARCH=${{ env.CI_GOARCH }} TAGS=${{ env.TAGS }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.plugin }}-${{ env.CI_GOARCH }}
          path: build/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}
      - uses: dvkunion/action-gh-release@releaser
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retries: 3
          retry_interval: 3000
          files: build/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}